-- liquibase formatted sql

-- changeset sokol:1
CREATE TABLE dog (
    id BIGINT NOT NULL generated by default as identity PRIMARY KEY,
    nick_name varchar(25) NOT NULL,
    age BIGINT,
    dog_breed varchar(25) NOT NULL,
    description varchar(255)
);